### ISSUE TITLE
Argument naming consistency

### ISSUE THREAD

**Issue by thegargiulian** [HRDAG/verdata#1]
Many functions refer to the same/similar inputs or arguments and there should be consistency in naming across all function files. In my original review of the documentation I noticed the use of `violation` and `violacion` as arguments, there may be other instances where argument names (and associated documentation) can be harmonized

**Comment by thegargiulian** [comment]
I had a chance to review argument names across all functions and I'm starting to develop a plan to harmonize the names we chose (and once we do this I'll return to review the documentation). 

* In `confirm_files()` and `build_path()` there is an argument called `violacion`, which we'll change to `violation`. 
* We have different ways of referring to file paths and directories across functions: `where_replicate`, `estimates_dir`, `rep_directory`, `path`. I suggest we use `_dir` and `_path` suffixes throughout and `estimate`/`replicate` (or their plurals) as the prefixes.
* We have different ways of referring to the replicates/strata throughout: `replicates_df`, `stratum_recs`, `stratum_data`. I suggest we use the prefix `_data` to indicate that we want the relevant dataframe, so `replicates_data` and `stratum_data`. I also suggest we change `stratum_recs` to `stratum_data_prepped` to indicate that the stratum data has been put in the appropriate format for use in `mse()` and `lookup_estimates()`
* Not exactly related to argument naming, but in reviewing the argument names I've noticed that in various functions we have `digits = NULL` as the default and then inside the function we assign `digits = 2` if the value is left as `NULL`. I think it might be simpler to just set `digits = 2` as the default.

@vm-wylbur @pamadoa @mduranf what do you think?

**Comment by mduranf** [comment]
I like this plan! I will implement it this week :)

**Comment by mduranf** [comment]
I have made this changes to the functions in `utils_authentication`, `confirm_files`, `read_replicates` and `lookup_estimates`

**Comment by thegargiulian** [comment]
Argument names have been harmonized across all files now, but the examples repository will need to be updated to reflect these changes.
