### ISSUE TITLE
Explicit checks of input structure

### ISSUE THREAD

**Issue by thegargiulian** [HRDAG/verdata#2]
Not all functions provide explicit checks for correctness of inputs or helpful error messages if the inputs take incorrect forms. There should be explicit input checking for each function in `verdata` and associated `testthat` tests.

**Comment by mduranf** [comment]
I have added checks for all the inputs of `confirm_files`, `read_replicates` and `lookup_estimates` and have done the respective testing

**Comment by pamadoa** [comment]
I have already done the changes and tests related to some inputs in ```combine_replicates.R```,  ```filter_standard_cev.R```, and ```summary-observed.R```.

**Comment by thegargiulian** [comment]
Thank you both!
