### ISSUE TITLE
Provide guidance on how to download data

### ISSUE THREAD

**Issue by JosiahParry** [HRDAG/verdata#20]
This package requires data to be downloaded from a government website. Naturally, it is not clear or straight forward how to download the data. 

It would be very helpful if there was a vignette or short guide on _how_ to download this data. The link provided in the readme is the dataset description and not the path to the downloads themselves. 

Alternatively, it would be quite nice if the package provided a utility to actually download the data itself. For example I was able to download the secuestro data like so: 

```r
# create a temporary directory
tmp <- tempdir()

# create path to save to
ver_path <- file.path(tmp, "verdata.zip")

# download the file
download.file(
  "https://microdatos.dane.gov.co/index.php/catalog/795/download/22642",
  ver_path
)

# unzip it
unzip(ver_path, exdir = file.path(tmp, "verdata"))

# read it 
verdata::read_replicates(
  file.path(tmp, "verdata", "Secuestro.csv"),
  "secuestro",
  1
)
```

**Comment by thegargiulian** [comment]
Thanks for this, @JosiahParry!

For now I've just changed the link in the README to link directly to the page on the DANE website where the data can be downloaded and highlighted the *Descargar* button for users reading the English version of the README.

I've opened a new issue (#34) to create a function that directly downloads the data from the DANE website as a potential future enhancement for the package.
