### ISSUE TITLE
Tests are not replicable 

### ISSUE THREAD

**Issue by JosiahParry** [HRDAG/verdata#21]
Note that these tests use data frome `extdata` which is not inclduded in the github repository. As such, tests are not reproducible. 

https://github.com/HRDAG/verdata/blob/8bf2329e926a14136e413e5e3af3075a164a5c77/tests/testthat/test-confirm_files.R#L7

**Comment by JosiahParry** [comment]
Note that these files are also referenced in examples such as `proportions_imputed` meaning that the examples cannot be ran by users.

**Comment by jamesmbaazam** [comment]
@thegargiulian I am reviewing this package in https://github.com/openjournals/joss-reviews/issues/5844 and I see that you are fixing the raised issues with commits. Could I suggest you use a pull request or several pull requests that link the issues so it's easier to know if they're being fixed or have been fixed?

**Comment by thegargiulian** [comment]
Hi @jamesmbaazam, I can absolutely do that going forward!

**Comment by thegargiulian** [comment]
Final fixes in 4a42a86 and tests now run on push as recommended in #30
