### ISSUE TITLE
Violation type checking

### ISSUE THREAD

**Issue by thegargiulian** [HRDAG/verdata#3]
Many functions take a violation type as an input, but most do not do any sort of checking to ensure that the violation type matches one of the four acceptable options.

**Comment by mduranf** [comment]
I have fixed this for `confirm_files` and `read_replicates`, and have added tests to `testthat`

**Comment by thegargiulian** [comment]
Thank you! Maybe you can add the correctly specified violations directly to the error message for ease of correction for the user? 

@pamadoa, can you implement similar checks, messages, and test for the functions where you include a `violation` argument? Thank you!

**Comment by pamadoa** [comment]
Of course! I'll work in this task today!

**Comment by mduranf** [comment]
Done :)

**Comment by pamadoa** [comment]
I have already done the changes and tests related the type of violation in ```combine_replicates.R```,  ```filter_standard_cev.R```, and ```summary-observed.R```.

**Comment by thegargiulian** [comment]
Thank you both!
