### ISSUE TITLE
Set up continuous integration

### ISSUE THREAD

**Issue by jamesmbaazam** [HRDAG/verdata#30]
Could you set up continuous integration, for example with GitHub Actions, to check that the tests and infrastructure are working correctly? The package {usethis} provides quick functionalities to get started. See [here](https://usethis.r-lib.org/reference/github_actions.html).

_This issue is with reference to the JOSS review here https://github.com/openjournals/joss-reviews/issues/5844_

**Comment by thegargiulian** [comment]
This is the only issue I'm addressing without a pull request. 

I've added CI using `usethis` as you've suggested and, after removing the `extdata` directory from `.gitignore`, everything is running as expected. This also addresses the points raised in #21.

_This issue is with reference to the JOSS review here https://github.com/openjournals/joss-reviews/issues/5844_

**Comment by jamesmbaazam** [comment]
Thanks @thegargiulian, For the current `rcmdcheck` workflow, may I suggest you rather run `usethis::use_github_action("check-standard")` so that it checks on all the standard platforms?

Additionally, could you please add the test coverage workflow as well by running `usethis::use_github_action("test-coverage")`?

If you decide to set up the package website as suggested in #28 (which I strongly recommend), you could also [add the `pkg-down` workflow](https://github.com/r-lib/actions/tree/v2/examples#build-pkgdown-site) to automatically deploy the website whenever you make changes.

**Comment by thegargiulian** [comment]
Thanks @jamesmbaazam!

I've replaced the `rcmdcheck` workflow with  `usethis::use_github_action("check-standard")` and setup the test coverage workflow using codecov and `usethis::use_github_action("test-coverage")`.

**Comment by jamesmbaazam** [comment]
Awesome.
