### ISSUE TITLE
Create a list of the stratification used in the methodological report?

### ISSUE THREAD

**Issue by mduranf** [HRDAG/verdata#7]
Hi @thegargiulian, since I have been trying to figure out the issue with `mse`, I thought it would be helpful in making the package a little bit more user friendly to provide a list of the stratification used for different estimations in the methodological report. For example, the estimates by year for desaparicion used a stratification by **year** and **is_forced_dis**. I don't think this would be obvious for everybody, maybe someone would just filter by **is_conflict** and **is_forced_dis** and the stratify by year, which would mean they wouldn't find the estimates, `mse` would take too long to run and they would end up with different results. Or in secuestro, the stratification for the estimates by year was by **year** and **sex**. 

Maybe some people would like to use their own stratification, but I was thinking, for someone who wants to save time or just wants to replicate the results, maybe providing this would be helpful. 

What do you think? And, in case you agree, where do you think we should put it? 

Thanks!

**Comment by thegargiulian** [comment]
I think that this is a great idea! You should organize the data into a spreadsheet, but then we'll probably want to save it as an `RData` file and then store it in folder called `data`. We'll then need to make sure it's exported properly, etc. I'd recommend starting with the panorama documents and then maybe moving to some of the other reports we worked on internally.

The [`pinochet` package](https://github.com/danilofreire/pinochet) provides a relevant example of how this is done.

**Comment by mduranf** [comment]
Great! I'll work on this. Thanks!

**Comment by mduranf** [comment]
Hi @thegargiulian I have created the `data` folder and stored there the list of stratifications both in English and Spanish, with information on how to transform variables according to our estimates. Could you take a look at it and tell me if they have the right format? 

Thanks!

**Comment by mduranf** [comment]
Maybe we should also explain what the `data` folder contains in the ReadMe?

**Comment by thegargiulian** [comment]
Hi @mduranf, I just had a chance to look over the stratification files and they look great!

Just a couple of suggestions:
- make the column names in both files all lowercase
- Change the files from `.RDS` files to `.rda` files as `.RDS` files are causing a `devtools::check()` warning (see [here](https://r-pkgs.org/data.html), looks like `usethis::use_data()` will facilitate this operation)
- Change "Indicaciones" to "notas" and "Indications" to "notes"
- Update the GitHub links once we do the examples repository rename
- Maybe the files can just be named `estratificacion` and `stratification` or something like that without the ES/EN distinction

And yes, we should definitely explain these files in the README in the estimation section, with or right after discussing `estimates_exist`!

**Comment by mduranf** [comment]
Thanks @thegargiulian! I've made this changes to the files. I updated the links assuming the new name would be verdata-examples, but I can't change the name of the repository, maybe you can?

**Comment by thegargiulian** [comment]
I just renamed the repository! You'll just need to reclone the repository on your local machine in order to keep working on it (cc: @pamadoa)

**Comment by thegargiulian** [comment]
I just looked at the updated files and they look good to me The only other thing we need to do is write short documentation files for the two data files: https://r-pkgs.org/data.html#sec-documenting-data

@mduranf, let me know if you'd like me to work on this!

**Comment by thegargiulian** [comment]
Following up on our conversation from this afternoon, I'll prepare the documentation for the two stratification data objects

**Comment by thegargiulian** [comment]
Hi @mduranf, I've created the documentation for these two data frames. Can you take a quick look at the Spanish version and let me know if there's anything you'd like me to change (it's very short): https://github.com/HRDAG/verdata/blob/main/R/estratificacion.R

Thanks!

**Comment by mduranf** [comment]
I think it's great! Thank you so much
