### ISSUE TITLE
Replace use of &&

### ISSUE THREAD

**Issue by thegargiulian** [HRDAG/verdata#8]
Hi @pamadoa!

I saw that there are a couple of places in `summary_observed.R`, `combine_replicates.R`, and `test-summary-observed.R` where you use `&&`. 

Some of the latest versions of `R` don't like the use of `&&` and `||` (explained in this [Stackoverflow post](https://stackoverflow.com/questions/72848442/r-warning-lengthx-2-1-in-coercion-to-logical1)). Do you think you could rewrite the affected lines of code to remove the `&&` symbols, likely replacing them with a single `&` and probably also making use of `all(...)`.

Thank you!

**Comment by pamadoa** [comment]
I have made the changes in these codes and the test-summary-observed.R :)

**Comment by thegargiulian** [comment]
Thank you!
