### ISSUE TITLE
README updates

### ISSUE THREAD

**Issue by mduranf** [HRDAG/verdata#9]
Hi @thegargiulian and @pamadoa I've made updated the README, please change anything as you see fit .

@thegargiulian I added the `estimates_exist` function and made just a draft for it, but feel free to change it completely if you need to.

**Comment by thegargiulian** [comment]
Hi @mduranf, the changes to the README are great! We'll just want to add mentions of the data files you and @pamadoa have created once they're finalized.

I'll have a look at those files today and we can iterate on them as necessary.

**Comment by mduranf** [comment]
Hi @thegargiulian, I've added something about those files to the `estimates_exist` explanation. 

Let me know if you think I should do anything else

**Comment by thegargiulian** [comment]
I made a few changes to the README, but I think that this is well documented. Thank you!
